// components/Footer.vue
<template>
  <footer>
    <div class="container">
      <div class="grid grid-cols-1 md:grid-cols-2 py-10 gap-[30px] md:gap-0">
        <div>
          <h1 class="text-xl md:text-3xl">This is my portfolio</h1>
          <p>eolnuha.com © copyright {{ new Date().getFullYear() }}</p>
        </div>
        <div>
          <h1 class="text-xl md:text-3xl">Find me on other social media</h1>
          <div class="flex justify-center gap-[10px]">
            <a href="https://www.linkedin.com/in/eolnuha/"
              ><span class="icon icon-linkedin"></span
            ></a>
            <a href="https://github.com/eolnuha"
              ><span class="icon icon-github"></span
            ></a>
            <a href="https://stackoverflow.com/users/14683130/eol-nuha"
              ><span class="icon icon-stackoverflow"></span
            ></a>
          </div>
        </div>
      </div>
    </div>
  </footer>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped>
footer {
  background: #1a1a1a;
  margin-top: 150px;
  h1 {
    color: white;
    text-align: center;
  }
  p {
    @apply text-gray-200;
    text-align: center;
  }
}
</style>

// app/components/footer.jsx
// @flow strict
import Link from 'next/link';

function Footer() {
  return (
    <div className="relative border-t bg-[#0d1224] border-[#353951] text-white">
      <div className="mx-auto px-6 sm:px-12 lg:max-w-[70rem] xl:max-w-[76rem] 2xl:max-w-[92rem] py-6 lg:py-10">
        <div className="flex justify-center -z-40">
          <div className="absolute top-0 h-[1px] w-1/2  bg-gradient-to-r from-transparent via-violet-500 to-transparent"></div>
        </div>
        <div className="flex flex-col md:flex-row items-center justify-between">
          <p className="text-sm">
            © Developer Portfolio by <Link target="_blank" href="https://www.linkedin.com/in/eolnuha/" className="text-[#16f2b3]">Eol Nuha</Link>
          </p>
        </div>
      </div>
    </div >
  );
};

export default Footer;
